builds:
  - binary: nepcal
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    main: ./cmd/nepcal

archives:
  - format: tar.gz

brews:
  - name: nepcal
    tap:
      owner: srishanbhattarai
      name: nepcal
    folder: Formula
    homepage: https://github.com/nepcal/nepcal
    description: Equivalent of Linux's cal, for Nepali dates
