# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nepcal < Formula
  desc "Equivalent of Linux's cal, for Nepali dates"
  homepage "https://github.com/nepcal/nepcal"
  version "1.2.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/srishanbhattarai/nepcal/releases/download/v1.2.1/nepcal_1.2.1_darwin_arm64.tar.gz"
      sha256 "2c7a1e8720e349172692265fcc93694af111a572a26bf7abdd15760839526938"

      def install
        bin.install "nepcal"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/srishanbhattarai/nepcal/releases/download/v1.2.1/nepcal_1.2.1_darwin_amd64.tar.gz"
      sha256 "d37e789ca3c60007b0624a1d33194e4160ed7fc73a0979f24704c01d6f892f99"

      def install
        bin.install "nepcal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/srishanbhattarai/nepcal/releases/download/v1.2.1/nepcal_1.2.1_linux_arm64.tar.gz"
      sha256 "fe5d80b5915832bca9d7a1e008b79bd8c4bf0d575de1e9b9a36b92c2bd83eb0d"

      def install
        bin.install "nepcal"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/srishanbhattarai/nepcal/releases/download/v1.2.1/nepcal_1.2.1_linux_amd64.tar.gz"
      sha256 "287173f752eeb0fded3b5c3ea5e390abc3a03d1e59fe685cb6e681656b269962"

      def install
        bin.install "nepcal"
      end
    end
  end
end
